# engram-v3/config.yaml
# Configuration file for keyboard layout optimization, controlling the entire pipeline.

#-----------------------------------------------------------------------
# Paths
#-----------------------------------------------------------------------
paths:
  input:
    two_key_comfort_scores_file: "input/estimated_bigram_scores.csv"
    one_key_comfort_scores_file: "input/estimated_key_scores.csv"
  output:
    layout_results_folder: "output/layouts"

#-----------------------------------------------------------------------
# Optimization Settings
#-----------------------------------------------------------------------
optimization:
  letters: "th"       # Letters to arrange
  keys: "df"          # Qwerty keys to position letters
  scoring:  
    bigram_weight: 0.5  # Weight for bigram / 2-key score
    letter_weight: 0.5  # Weight for letter / 1-key score
  nlayouts: 3           # Number of top layouts to display and save

#-----------------------------------------------------------------------
# Layout Settings
#-----------------------------------------------------------------------
layout:
  # Define the keyboard positions
  positions:
    right:
      top: ['u', 'i', 'o', 'p']
      home: ['j', 'k', 'l', ';']
      bottom: ['m', ',', '.', '/']
    left:
      top: ['q', 'w', 'e', 'r']
      home: ['a', 's', 'd', 'f']
      bottom: ['z', 'x', 'c', 'v']
  
  # Define position equivalence mappings  
  position_mappings:
    right_to_left:
      # Top row
      'u': 'r'
      'i': 'e'
      'o': 'w'
      'p': 'q'
      # Home row
      'j': 'f'
      'k': 'd'
      'l': 's'
      ';': 'a'
      # Bottom row
      'm': 'v'
      ',': 'c'
      '.': 'x'
      '/': 'z'

#-----------------------------------------------------------------------
# Visualization Settings
#-----------------------------------------------------------------------
visualization:
  keyboard_template: |
    ╭───────────────────────────────────────────────╮
    │ Layout: {title:<34}    │
    ├─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┤
    │  Q  │  W  │  E  │  R  ║  U  │  I  │  O  │  P  │
    │ {q:^3} │ {w:^3} │ {e:^3} │ {r:^3} ║ {u:^3} │ {i:^3} │ {o:^3} │ {p:^3} │
    ├─────┼─────┼─────┼─────╫─────┼─────┼─────┼─────┤
    │  A  │  S  │  D  │  F  ║  J  │  K  │  L  │  ;  │
    │ {a:^3} │ {s:^3} │ {d:^3} │ {f:^3} ║ {j:^3} │ {k:^3} │ {l:^3} │ {sc:^3} │
    ├─────┼─────┼─────┼─────╫─────┼─────┼─────┼─────┤
    │  Z  │  X  │  C  │  V  ║  M  │  ,  │  .  │  /  │
    │ {z:^3} │ {x:^3} │ {c:^3} │ {v:^3} ║ {m:^3} │ {cm:^3} │ {dt:^3} │ {sl:^3} │
    ╰─────┴─────┴─────┴─────╨─────┴─────┴─────┴─────╯

