# engram-v3/config.yaml
# Configuration file for keyboard layout optimization, controlling the entire pipeline.

#-----------------------------------------------------------------------
# Data Settings
#-----------------------------------------------------------------------
data:
  bigram_scores_file: "data/estimated_bigram_scores.csv"
  key_scores_file: "data/estimated_key_scores.csv"
  output_dir: "output/layouts"

#-----------------------------------------------------------------------
# Optimization Settings
#-----------------------------------------------------------------------
optimization:
  letters: "etao"  # Letters to arrange
  keys: "dfjk"  # Qwerty keys to arrange letters
  scoring:
    bigram_frequency_weight: 0.25  # Weight for bigram frequency scores
    letter_frequency_weight: 0.25  # Weight for letter frequency scores
    comfort_weight: 0.5    # Weight for comfort scores

#-----------------------------------------------------------------------
# Layout Settings
#-----------------------------------------------------------------------
layout:
  # Define the keyboard positions
  positions:
    right:
      top: ['u', 'i', 'o', 'p']
      home: ['j', 'k', 'l', ';']
      bottom: ['m', ',', '.', '/']
    left:
      top: ['q', 'w', 'e', 'r']
      home: ['a', 's', 'd', 'f']
      bottom: ['z', 'x', 'c', 'v']
  
  # Define position equivalence mappings  
  position_mappings:
    right_to_left:
      # Top row
      'u': 'r'
      'i': 'e'
      'o': 'w'
      'p': 'q'
      # Home row
      'j': 'f'
      'k': 'd'
      'l': 's'
      ';': 'a'
      # Bottom row
      'm': 'v'
      ',': 'c'
      '.': 'x'
      '/': 'z'

#-----------------------------------------------------------------------
# Visualization Settings
#-----------------------------------------------------------------------
visualization:
  keyboard_template: |
    ╭───────────────────────────────────────────────╮
    │ Layout: {title:<34}    │
    ├─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┤
    │  Q  │  W  │  E  │  R  ║  U  │  I  │  O  │  P  │
    │ {q:^3} │ {w:^3} │ {e:^3} │ {r:^3} ║ {u:^3} │ {i:^3} │ {o:^3} │ {p:^3} │
    ├─────┼─────┼─────┼─────╫─────┼─────┼─────┼─────┤
    │  A  │  S  │  D  │  F  ║  J  │  K  │  L  │  ;  │
    │ {a:^3} │ {s:^3} │ {d:^3} │ {f:^3} ║ {j:^3} │ {k:^3} │ {l:^3} │ {sc:^3} │
    ├─────┼─────┼─────┼─────╫─────┼─────┼─────┼─────┤
    │  Z  │  X  │  C  │  V  ║  M  │  ,  │  .  │  /  │
    │ {z:^3} │ {x:^3} │ {c:^3} │ {v:^3} ║ {m:^3} │ {cm:^3} │ {dt:^3} │ {sl:^3} │
    ╰─────┴─────┴─────┴─────╨─────┴─────┴─────┴─────╯

#-----------------------------------------------------------------------
# Logging Settings
#-----------------------------------------------------------------------
logging:
  level: "INFO"
  file: "output/logs/layout_optimization.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"