# engram-v3/config.yaml
# Configuration file for keyboard layout optimization.

#-----------------------------------------------------------------------
# Paths
#-----------------------------------------------------------------------
paths:
  input:
    two_key_comfort_scores_file: "input/estimated_bigram_scores.csv"
    one_key_comfort_scores_file: "input/estimated_key_scores.csv"
  output:
    layout_results_folder: "output/layouts"

#-----------------------------------------------------------------------
# Optimization Settings
#-----------------------------------------------------------------------
# Left home block of 12 keys in descending comfort order: FDSVERAWCQXZ
# Letters in descending frequency: etaoinsrhldcumfpgwybvkxjqz
# Vowels/consonants: eaoiu / tnsrhld cmfpgwybvkxj [qz]
# Most comfortable keys (left/right): FDSVERAW / JKLMIU;O
# Goal: Optimally arrange the 24 most frequent letters (not q or z)
#       in the 24 home block keys.
# (1) Assign E and T (most common letters) to the most comfortable keys.
# (2) Arrange 5 vowels in the 6 most comfortable keys on the left side of the keyboard
#      .

# (2) Arrange 8 consonants (with > median frequency "u") 
#     within the remaining keys of the 16 most comfortable keys.
# (3) Optimally arrange the 11 remaining letters (not q or z)
#     in the 11 remaining home block keys.
optimization:

  letters_assigned: ""          # Letters already assigned to keys_assigned
  keys_assigned:    ""          # Keys assigned letters_assigned

  letters_to_constrain: "et"  # Subset of letters_to_assign to arrange within keys_to_constrain
  keys_to_constrain: "FDJK"   # Subset of keys_to_assign to constrain arrangement of letters_to_constrain

  letters_to_assign: "etaoiunsrhldc"  # 13 Letters to arrange
  keys_to_assign: "FDSVERAJKLMIU"     # 13 Keys to arrange letters_to_assign
  scoring:  
    bigram_weight: 0.5  # Weight for bigram / 2-key score
    letter_weight: 0.5  # Weight for letter / 1-key score
  nlayouts: 10          # Number of top layouts to display and save

#-----------------------------------------------------------------------
# Layout Settings
#-----------------------------------------------------------------------
layout:
  # Define the keyboard positions
  positions:
    right:
      top: ['u', 'i', 'o', 'p']
      home: ['j', 'k', 'l', ';']
      bottom: ['m', ',', '.', '/']
    left:
      top: ['q', 'w', 'e', 'r']
      home: ['a', 's', 'd', 'f']
      bottom: ['z', 'x', 'c', 'v']
  
  # Define position equivalence mappings  
  position_mappings:
    right_to_left:
      # Top row
      'u': 'r'
      'i': 'e'
      'o': 'w'
      'p': 'q'
      # Home row
      'j': 'f'
      'k': 'd'
      'l': 's'
      ';': 'a'
      # Bottom row
      'm': 'v'
      ',': 'c'
      '.': 'x'
      '/': 'z'

#-----------------------------------------------------------------------
# Visualization Settings
#-----------------------------------------------------------------------
visualization:
  keyboard_template: |
    ╭───────────────────────────────────────────────╮
    │ Layout: {title:<34}    │
    ├─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┤
    │ {q:^3} │ {w:^3} │ {e:^3} │ {r:^3} ║ {u:^3} │ {i:^3} │ {o:^3} │ {p:^3} │
    ├─────┼─────┼─────┼─────╫─────┼─────┼─────┼─────┤
    │ {a:^3} │ {s:^3} │ {d:^3} │ {f:^3} ║ {j:^3} │ {k:^3} │ {l:^3} │ {sc:^3} │
    ├─────┼─────┼─────┼─────╫─────┼─────┼─────┼─────┤
    │ {z:^3} │ {x:^3} │ {c:^3} │ {v:^3} ║ {m:^3} │ {cm:^3} │ {dt:^3} │ {sl:^3} │
    ╰─────┴─────┴─────┴─────╨─────┴─────┴─────┴─────╯
  keyboard_qwerty_template: |
    ╭───────────────────────────────────────────────╮
    │ Layout: {title:<34}    │
    ├─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┤
    │  Q  │  W  │  E  │  R  ║  U  │  I  │  O  │  P  │
    │ {q:^3} │ {w:^3} │ {e:^3} │ {r:^3} ║ {u:^3} │ {i:^3} │ {o:^3} │ {p:^3} │
    ├─────┼─────┼─────┼─────╫─────┼─────┼─────┼─────┤
    │  A  │  S  │  D  │  F  ║  J  │  K  │  L  │  ;  │
    │ {a:^3} │ {s:^3} │ {d:^3} │ {f:^3} ║ {j:^3} │ {k:^3} │ {l:^3} │ {sc:^3} │
    ├─────┼─────┼─────┼─────╫─────┼─────┼─────┼─────┤
    │  Z  │  X  │  C  │  V  ║  M  │  ,  │  .  │  /  │
    │ {z:^3} │ {x:^3} │ {c:^3} │ {v:^3} ║ {m:^3} │ {cm:^3} │ {dt:^3} │ {sl:^3} │
    ╰─────┴─────┴─────┴─────╨─────┴─────┴─────┴─────╯

