# optimize_layouts/config.yaml
# Configuration file for item-to-position layout optimization.

#-----------------------------------------------------------------------
# Paths
#-----------------------------------------------------------------------
paths:
  input:
    item_scores_file:          "input/letter_frequencies_english.csv"
    item_pair_scores_file:     "input/letter_pair_frequencies_english.csv"
    position_scores_file:      "input/key_comfort_estimates.csv"
    position_pair_scores_file: "input/key_pair_comfort_estimates.csv"
  output:
    layout_results_folder:     "output/layouts"

#-----------------------------------------------------------------------
# Optimization Settings
#-----------------------------------------------------------------------
optimization:

  items_to_assign:     "etaoinsrh" #ldcu"   # items to arrange in positions
  positions_to_assign: "FDSVERAJKL" #MIU;"  # available positions

  items_to_constrain:     "eta"           # Subset of items_to_assign to arrange within positions_to_constrain
  positions_to_constrain: "VERAJK"         # Subset of positions_to_assign to constrain arrangement of items_to_constrain

  items_assigned:        ""              # Items already assigned to positions
  positions_assigned:    ""              # Positions that are already filled 

  scoring:  
    item_weight: 0.5                     # Weight for single-item scoring
    item_pair_weight: 0.5                # Weight for item_pair scoring
    item_scale: "log10"
    position_scale: "linear"

  nlayouts: 100                          # Number of top layouts to display and save

#-----------------------------------------------------------------------
# Visualization Settings
#-----------------------------------------------------------------------
visualization:
  print_keyboard: True
  keyboard_template: |
    ╭───────────────────────────────────────────────╮
    │ Layout: {title:<34}    │
    ├─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┤
    │ {q:^3} │ {w:^3} │ {e:^3} │ {r:^3} ║ {u:^3} │ {i:^3} │ {o:^3} │ {p:^3} │
    ├─────┼─────┼─────┼─────╫─────┼─────┼─────┼─────┤
    │ {a:^3} │ {s:^3} │ {d:^3} │ {f:^3} ║ {j:^3} │ {k:^3} │ {l:^3} │ {sc:^3} │
    ├─────┼─────┼─────┼─────╫─────┼─────┼─────┼─────┤
    │ {z:^3} │ {x:^3} │ {c:^3} │ {v:^3} ║ {m:^3} │ {cm:^3} │ {dt:^3} │ {sl:^3} │
    ╰─────┴─────┴─────┴─────╨─────┴─────┴─────┴─────╯
  qwerty_keyboard_template: |
    ╭───────────────────────────────────────────────╮
    │ Layout: {title:<34}    │
    ├─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┤
    │  Q  │  W  │  E  │  R  ║  U  │  I  │  O  │  P  │
    │ {q:^3} │ {w:^3} │ {e:^3} │ {r:^3} ║ {u:^3} │ {i:^3} │ {o:^3} │ {p:^3} │
    ├─────┼─────┼─────┼─────╫─────┼─────┼─────┼─────┤
    │  A  │  S  │  D  │  F  ║  J  │  K  │  L  │  ;  │
    │ {a:^3} │ {s:^3} │ {d:^3} │ {f:^3} ║ {j:^3} │ {k:^3} │ {l:^3} │ {sc:^3} │
    ├─────┼─────┼─────┼─────╫─────┼─────┼─────┼─────┤
    │  Z  │  X  │  C  │  V  ║  M  │  ,  │  .  │  /  │
    │ {z:^3} │ {x:^3} │ {c:^3} │ {v:^3} ║ {m:^3} │ {cm:^3} │ {dt:^3} │ {sl:^3} │
    ╰─────┴─────┴─────┴─────╨─────┴─────┴─────┴─────╯

