# optimize_layouts/config.yaml
# Configuration file for item-to-position layout optimization.

#-----------------------------------------------------------------------
# Paths
#-----------------------------------------------------------------------
paths:
  input:
    item_scores_file:          "input/letter_frequencies_english.csv"
    item_pair_scores_file:     "input/letter_pair_frequencies_english.csv"
    position_scores_file:      "input/key_comfort_estimates.csv"
    position_pair_scores_file: "input/key_pair_comfort_estimates.csv"
  output:
    layout_results_folder:     "output/layouts"

#-----------------------------------------------------------------------
# Optimization Settings
#-----------------------------------------------------------------------
optimization:

  items_to_assign:     "ething" #eraog" #ldcu"   # items to arrange in positions
  positions_to_assign: "FDSV" #E" #RAWCQ" #X" #Z" #   JKLM" #IU;"  # available positions

  items_to_constrain:     "et"         # Subset of items_to_assign to arrange within positions_to_constrain
  positions_to_constrain: "FDSV"       # Subset of positions_to_assign to constrain arrangement of items_to_constrain

  items_assigned:        ""            # Items already assigned to positions
  positions_assigned:    ""            # Positions that are already filled 

  scoring:  
    item_weight: 1                     # Weight for single-item scoring
    item_pair_weight: 0                # Weight for item_pair scoring

  nlayouts: 1                          # Number of top layouts to display and save

#-----------------------------------------------------------------------
# Visualization Settings
#-----------------------------------------------------------------------
visualization: 
  print_keyboard: True
